app = "stock-market-ml"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"
  FLASK_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
