version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - ml-service

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=stock_market
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=${JWT_SECRET:-your-dev-secret-key}
      - JWT_EXPIRES_IN=24h
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_market
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
