services:
  - type: web
    name: stock-market-platform-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: ML_SERVICE_URL
        value: https://stock-market-platform-ml.onrender.com
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    healthCheckPath: /api/health
